const bscData = [
  {
    programmeName: "B.Sc (Biotechnology)",
    programmeId: "UG_100",
    subName: "Bioethics And Biosafety",
    subCode: "CC_13",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Bioinformatics",
    subCode: "DSE_01",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Genomics And Proteomics",
    subCode: "CC_11",
    one: "2012",
    two: "2013",
    three: "2014",
  },
];
const baData = [
  {
    programmeName: "B.Sc (Biotechnology)",
    programmeId: "UG_100",
    subName: "Bioethics And Biosafety",
    subCode: "CC_13",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Bioinformatics",
    subCode: "DSE_01",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Genomics And Proteomics",
    subCode: "CC_11",
    one: "2012",
    two: "2013",
    three: "2014",
  },
];
const bcomData = [
  {
    programmeName: "B.Sc (Biotechnology)",
    programmeId: "UG_100",
    subName: "Bioethics And Biosafety",
    subCode: "CC_13",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Bioinformatics",
    subCode: "DSE_01",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Genomics And Proteomics",
    subCode: "CC_11",
    one: "2012",
    two: "2013",
    three: "2014",
  },
];

const bcaData = [
  {
    programmeName: "B.Sc (Biotechnology)",
    programmeId: "UG_100",
    subName: "Bioethics And Biosafety",
    subCode: "CC_13",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Bioinformatics",
    subCode: "DSE_01",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Genomics And Proteomics",
    subCode: "CC_11",
    one: "2012",
    two: "2013",
    three: "2014",
  },
];
const biotechData = [
  {
    programmeName: "B.Sc (Biotechnology)",
    programmeId: "UG_100",
    subName: "Bioethics And Biosafety",
    subCode: "CC_13",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Bioinformatics",
    subCode: "DSE_01",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Genomics And Proteomics",
    subCode: "CC_11",
    one: "2012",
    two: "2013",
    three: "2014",
  },
];
const mscData = [
  {
    programmeName: "B.Sc (Biotechnology)",
    programmeId: "UG_100",
    subName: "Bioethics And Biosafety",
    subCode: "CC_13",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Bioinformatics",
    subCode: "DSE_01",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Genomics And Proteomics",
    subCode: "CC_11",
    one: "2012",
    two: "2013",
    three: "2014",
  },
];
const maData = [
  {
    programmeName: "B.Sc (Biotechnology)",
    programmeId: "UG_100",
    subName: "Bioethics And Biosafety",
    subCode: "CC_13",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Bioinformatics",
    subCode: "DSE_01",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Genomics And Proteomics",
    subCode: "CC_11",
    one: "2012",
    two: "2013",
    three: "2014",
  },
];
const mcomData = [
  {
    programmeName: "B.Sc (Biotechnology)",
    programmeId: "UG_100",
    subName: "Bioethics And Biosafety",
    subCode: "CC_13",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Bioinformatics",
    subCode: "DSE_01",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Genomics And Proteomics",
    subCode: "CC_11",
    one: "2012",
    two: "2013",
    three: "2014",
  },
];

const mcaData = [
  {
    programmeName: "B.Sc (Biotechnology)",
    programmeId: "UG_100",
    subName: "Bioethics And Biosafety",
    subCode: "CC_13",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Bioinformatics",
    subCode: "DSE_01",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Genomics And Proteomics",
    subCode: "CC_11",
    one: "2012",
    two: "2013",
    three: "2014",
  },
];
export default bscData;
export { bscData, baData, bcomData, bcaData, biotechData };
export { mscData, maData, mcomData, mcaData };
