const bscData = [
  {
    programmeName: "B.Sc (Physics)",
    programmeId: "UG_941",
    subName: "Paper-V",
    subCode: "CC_941_1",
    one: "2018",
    two: "2019",
    three: "2020",
  },
  {
    programmeName: "B.Sc (Physics)",
    programId: "UG_941",
    subName: "Paper-VI",
    subCode: "CC_941_2",
    one: "2018",
    two: "2019",
    three: "2020",
  },
  {
    programmeName: "B.Sc (Physics)",
    programId: "UG_941",
    subName: "Paper-VII",
    subCode: "CC_941_3",
    one: "2018",
    two: "2019",
    three: "2020",
  },
];
const baData = [
  {
    programmeName: "B.Sc (Chemistry)",
    programmeId: "UG_942",
    subName: "Paper-V",
    subCode: "CC_942_1",
    one: "2018",
    two: "2019",
    three: "2020",
  },
  {
    programmeName: "B.Sc (Chemistry)",
    programId: "UG_942",
    subName: "Paper-VI",
    subCode: "CC_942_2",
    one: "2018",
    two: "2019",
    three: "2020",
  },
  {
    programmeName: "B.Sc (Chemistry)",
    programId: "UG_942",
    subName: "Paper-VII",
    subCode: "CC_942_3",
    one: "2018",
    two: "2019",
    three: "2020",
  },
];
const bcomData = [
  {
    programmeName: "B.Sc (Statistics)",
    programmeId: "UG_947",
    subName: "Paper-V",
    subCode: "CC_947_1",
    one: "2018",
    two: "2019",
    three: "-",
  },
  {
    programmeName: "B.Sc (Statistics)",
    programmeId: "UG_947",
    subName: "Paper-VI",
    subCode: "CC_947_2",
    one: "2018",
    two: "2019",
    three: "-",
  },
  {
    programmeName: "B.Sc (Statistics)",
    programmeId: "UG_947",
    subName: "Paper-VII",
    subCode: "CC_947_3",
    one: "2018",
    two: "2019",
    three: "-",
  },
];

const bcaData = [
  {
    programmeName: "B.A. (History)",
    programmeId: "UG_9312",
    subName: "Paper-V",
    subCode: "CC_9312_1",
    one: "2018",
    two: "2019",
    three: "2020",
  },
  {
    programmeName: "B.A. (History)",
    programmeId: "UG_9312",
    subName: "Paper-VI",
    subCode: "CC_9312_2",
    one: "2018",
    two: "2019",
    three: "2020",
  },
  {
    programmeName: "B.A. (History)",
    programmeId: "UG_9312",
    subName: "Paper-VII",
    subCode: "CC_9312_3",
    one: "2018",
    two: "2019",
    three: "2020",
  },
];
const biotechData = [
  {
    programmeName: "B.A. (Psychology)",
    programmeId: "UG_9316",
    subName: "Paper-V",
    subCode: "CC_9316_1",
    one: "2018",
    two: "2019",
    three: "2020",
  },
  {
    programmeName: "B.A. (Psychology)",
    programmeId: "UG_9316",
    subName: "Paper-VI",
    subCode: "CC_9316_2",
    one: "2018",
    two: "2019",
    three: "2020",
  },
  {
    programmeName: "B.A. (Psychology)",
    programmeId: "UG_9316",
    subName: "Paper-VII",
    subCode: "CC_9316_3",
    one: "2018",
    two: "2019",
    three: "2020",
  },
];
const mscData = [
  {
    programmeName: "B.Sc (Biotechnology)",
    programmeId: "UG_100",
    subName: "Bioethics And Biosafety",
    subCode: "CC_13",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Bioinformatics",
    subCode: "DSE_01",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Genomics And Proteomics",
    subCode: "CC_11",
    one: "2012",
    two: "2013",
    three: "2014",
  },
];
const maData = [
  {
    programmeName: "B.Sc (Biotechnology)",
    programmeId: "UG_100",
    subName: "Bioethics And Biosafety",
    subCode: "CC_13",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Bioinformatics",
    subCode: "DSE_01",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Genomics And Proteomics",
    subCode: "CC_11",
    one: "2012",
    two: "2013",
    three: "2014",
  },
];
const mcomData = [
  {
    programmeName: "B.Sc (Biotechnology)",
    programmeId: "UG_100",
    subName: "Bioethics And Biosafety",
    subCode: "CC_13",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Bioinformatics",
    subCode: "DSE_01",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Genomics And Proteomics",
    subCode: "CC_11",
    one: "2012",
    two: "2013",
    three: "2014",
  },
];

const mcaData = [
  {
    programmeName: "B.Sc (Biotechnology)",
    programmeId: "UG_100",
    subName: "Bioethics And Biosafety",
    subCode: "CC_13",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Bioinformatics",
    subCode: "DSE_01",
    one: "2012",
    two: "2013",
    three: "2014",
  },
  {
    programmeName: "B.Sc (Biotechnology)",
    programId: "UG_100",
    subName: "Genomics And Proteomics",
    subCode: "CC_11",
    one: "2012",
    two: "2013",
    three: "2014",
  },
];
export default bscData;
export { bscData, baData, bcomData, bcaData, biotechData };
export { mscData, maData, mcomData, mcaData };
